title: William Olichney
description: Business Analytics graduate student versed in data analysis, project management, and communication between 
Mandarin and English-speaking audiences. Proven experience in analytics, events, and client interaction to meet various roles. Especially vested in roles relating to public policy and international trade
logo: https://github.com/wkolichney/wkolichney.github.io/blob/my_pages/assets/img/William%20O%20portrait.jpg?raw=true
theme: jekyll-theme-minimal
