title: William Olichney
logo: https://github.com/wkolichney/wkolichney.github.io/blob/main/assets/William%20O%20portrait.jpg?raw=true
description: show text below
show_downloads: true
theme: jekyll-theme-minimal
