title: William Olichney
description: William Olichney's portfolio
logo: https://github.com/wkolichney/wkolichney.github.io/blob/main/assets/William%20O%20portrait.jpg?raw=true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

