title: William Olichney
description: William Olichney's portfolio
logo: https://github.com/wkolichney/wkolichney.github.io/blob/main/assets/img/William%20O%20portrait.jpg?raw=true
#theme: jekyll-theme-minima

