title: William Olichney
#logo: https://github.com/wkolichney/wkolichney.github.io/blob/main/assets/William%20O%20portrait.jpg?raw=true
remote_theme: jekyll-theme-minimal
description: text below image
show_downloads: true

