title: William Olichney
logo: https://github.com/wkolichney/wkolichney.github.io/blob/my_pages/assets/img/William%20O%20portrait.jpg?raw=true
description: [![Conference Presentation](https://img.youtube.com/vi/TKMt_1rrYmk/0.jpg)](https://www.youtube.com/watch?v=TKMt_1rrYmk&t=11738s)
show_downloads: true
theme: jekyll-theme-minimal
