title: William Olichney
logo: https://raw.githubusercontent.com/wkolichney/wkolichney.github.io/main/assets/Commencement.JPG
description: show text below
show_downloads: true
theme: jekyll-theme-minimal
